/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ParseEvent {
  DocumentLocation: {
    S3Object: {
      Bucket: string;
      Name: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  OutputConfig?: {
    S3Bucket: string;
    S3Prefix: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
